#!/usr/bin/env bash
#
# apply-state.sh — regenerate the config files that kitty and tmux include from
# the machine-local state in ~/.local/state/dotfiles.
#
# Usage:
#   apply-state.sh                    regenerate from current state
#   apply-state.sh --theme latte      set the flavour, then regenerate
#   apply-state.sh --padding off      set kitty padding, then regenerate
#
# This is the only place that knows how to turn state values into on-disk
# config, so quick-setup.sh, the toggle scripts and a manual re-run all produce
# identical results.
#
# Nothing is symlinked. kitty and tmux each include a small generated file from
# the state dir, which in turn points at the committed catppuccin-<flavour>
# file. Selecting a theme by symlinking a tracked path made the choice show up
# as a repo modification, which is what this replaces.
set -euo pipefail

DOTFILES="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=lib/state.sh
. "$DOTFILES/scripts/lib/state.sh"

usage() {
  cat >&2 <<EOF
Usage: $(basename "$0") [--theme mocha|latte] [--padding on|off]

With no arguments, regenerates the generated config from existing state.
EOF
  exit 1
}

while [ $# -gt 0 ]; do
  case "$1" in
    --theme)
      [ $# -ge 2 ] || usage
      case "$2" in
        mocha | latte) ;;
        *)
          echo "apply-state: unknown theme '$2' (expected mocha or latte)" >&2
          exit 1
          ;;
      esac
      state_set theme "$2"
      shift 2
      ;;
    --padding)
      [ $# -ge 2 ] || usage
      case "$2" in
        on | off) ;;
        *)
          echo "apply-state: unknown padding '$2' (expected on or off)" >&2
          exit 1
          ;;
      esac
      state_set padding "$2"
      shift 2
      ;;
    -h | --help) usage ;;
    *)
      echo "apply-state: unexpected argument '$1'" >&2
      usage
      ;;
  esac
done

theme="$(state_get theme "$DEFAULT_THEME")"
padding="$(state_get padding "$DEFAULT_PADDING")"

# Padding width used when padding is enabled. Kept in step with the
# window_padding_width in kitty/kitty.conf.
PADDING_WIDTH=7
[ "$padding" = "off" ] && PADDING_WIDTH=0

mkdir -p "$STATE_DIR"

# Referencing ~/.config/{kitty,tmux} rather than $DOTFILES keeps the generated
# files valid regardless of where the repo is checked out on another machine.
#
# No theme here: kitty's colours are pinned in kitty.conf. Switching them would
# only affect newly opened windows, since kitty won't repaint existing ones
# without remote control, so tmux owns every themed surface instead.
cat >"$STATE_DIR/kitty-generated.conf" <<EOF
# Generated by scripts/apply-state.sh — do not edit.
# Source of truth: $STATE_DIR/padding
window_padding_width $PADDING_WIDTH
EOF

cat >"$STATE_DIR/tmux-generated.conf" <<EOF
# Generated by scripts/apply-state.sh — do not edit.
# Source of truth: $STATE_DIR/theme
source-file ~/.config/tmux/catppuccin-$theme.conf
EOF

# zsh has no ~/.config/zsh symlink (its config is sourced from $DOTFILES by an
# absolute path already), so this points straight at the committed palette. The
# path is baked at generation time, but this file is machine-local and rewritten
# on every apply-state run, so a re-checkout elsewhere regenerates it correctly.
cat >"$STATE_DIR/zsh-generated.sh" <<EOF
# Generated by scripts/apply-state.sh — do not edit.
# Source of truth: $STATE_DIR/theme
. "$DOTFILES/zsh/catppuccin-$theme.sh"
EOF

# Claude Code watches ~/.claude/themes/ and live-reloads on change. Copy the
# appropriate flavour file so running instances repaint immediately.
mkdir -p "$HOME/.claude/themes"
cp "$DOTFILES/claude/catppuccin-$theme.json" "$HOME/.claude/themes/catppuccin.json"

printf 'theme=%s padding=%s\n' "$theme" "$padding"
